services:
  mariadb:
    image: mariadb:12
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASS}"
      MARIADB_DATABASE: RegistrosSensor
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend/DockerBuild
    environment:
      DB_HOST: mariadb
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_NAME: RegistrosSensor

      # ==== MQTT PÃšBLICO ====
      MQTT_BROKER_URL: mqtt://test.mosquitto.org:1883

    ports:
      - "3000:3000"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
